<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>AvalonHumans.AI.Package</AssemblyName>
    <RootNamespace>AvalonHumans.AI.Package</RootNamespace>
    <Version>0.1.0</Version>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\avalon-ai-runtime\src\AvalonAI.Contracts\AvalonAI.Contracts.csproj" />
  </ItemGroup>
</Project>
