<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>AvalonBroodmotherCompanion.AI.Package.V2</AssemblyName>
    <RootNamespace>AvalonBroodmotherCompanion.AI.Package.V2</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\avalon-ai-runtime\src\AvalonAI.Contracts.V2\AvalonAI.Contracts.V2.csproj" />
  </ItemGroup>
</Project>
