<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <NuGetAudit>false</NuGetAudit>
    <UnityManagedDir Condition="'$(UnityManagedDir)' == ''"><local-path>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Tainted.Armour.Unity\Tainted.Armour.Unity.csproj" />
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(UnityManagedDir)\UnityEngine.CoreModule.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="UnityEngine.SharedInternalsModule">
      <HintPath>$(UnityManagedDir)\UnityEngine.SharedInternalsModule.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
