<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>Tainted.Armour.Fixtures</AssemblyName>
    <RootNamespace>Tainted.Armour.Fixtures</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Tainted.Armour\Tainted.Armour.csproj" />
  </ItemGroup>
</Project>
